/* CREATE DATABASE */
CREATE DATABASE Task1;

/* SWITCH TO CREATED DATABASE */
USE Task1;

/* ADD ALL TABLES */
CREATE TABLE regions(
    REGION_ID INT,
    REGION_NAME VARCHAR(25)
);
CREATE TABLE countries(
    COUNTRY_ID INT,
    COUNTRY_NAME VARCHAR(40),
    REGION_ID INT
);
CREATE TABLE locations(
    LOCATION_ID INT,
    STREET_ADDRESS VARCHAR(25),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(12),
    COUNTRY_ID INT
);
    CREATE TABLE departments(
    DEPARTMENT_ID INT,
    DEPARTMENT_NAME VARCHAR(30),
    MANAGER_ID INT,
    LOCATION_ID INT
);
CREATE TABLE employees(
    EMPLOYEE_ID INT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25),
    EMAIL VARCHAR(25),
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE,
    JOB_ID VARCHAR(10),
    SALARY INT,
    COMMISSION_PCT INT,
    MANAGER_ID INT,
    DEPARTMENT_ID INT
);
CREATE TABLE jobs(
    JOB_ID VARCHAR(10),
    JOB_TITLE VARCHAR(35),
    MIN_SALARY INT,
    MAX_SALARY INT
);
CREATE TABLE job_history(
    EMPLOYEE_ID INT,
    START_DATE DATE,
    END_DATE DATE,
    JOB_ID VARCHAR(10),
    DEPARTMENT_ID INT
);
CREATE TABLE job_grades(
    GRADE_LEVEL VARCHAR(2),
    LOWEST_SAL INT,
    HIGHEST_SAL INT
);

--INSERT INTO regions
